---
title: "Compte rendu reunion du 16/02/2017"
author: "Romain Francois"
date: "16/02/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Compte Rendu réunion telephonique du 16 fevrier 2017

Présents: Romain François, Hadrien Commenges, Juste Raimbault

Objet de la réunion: nous avons abordé les différents jeux de données utilisés par les applications.

Le chargement des différents jeux de données est effectué dans le fichier `global.R`, chacun charge des jeux de données différents
dans sa partie du code. Ces jeux de données peuvent être:
  - Des fichiers `.RData` chargés avec `load`. Nous avons convenu de plutot utiliser des fichiers `.rds` à l'avenir et de charger les
    objets séparement. En effet certains `.RData` contiennent plusieurs objets et ce n'est pas toujours très clair. Il y a 5 fichiers `.RData` utilisés.
  - Des fichiers `.csv`
  - Des fichiers `.sqlite3` qui sont cela dit vide parce que trop gros pour github. Nous avons évoqué [LFS](https://git-lfs.github.com) qui pourrait etre une solution

## Actions

Les différentes applications utilisent des données qui leur sont propres, mais aussi des données
communes (ou qui pourraient, devraient l'etre). Il y a un travail d'unification
de ces données à faire.

Faire le point avec les auteurs de chaque application pour identifier
les données réellement utilisées.

deplacement des fonctions dans le package. Pour l'instant on a des fonctions
dans le package et dans le global.R.

simplification de la reactivité. certains reactives ne sont en fait pas ou peu reactifs,
on pourra les reconditionner en fonctions du package afin de simplifier
le fichier server.R. 

## Structure

On retrouve plusieurs jeux de données avec une structure similaire,
`hadriTerms`, `justeTerms`, ...

La première colonne identifieun article.
Les colonnes suivantes sont des proportion d'appartenance de cet article à des
groupes de mots clés.

A priori donc, en sommant ces proportions on retrouve 1. A verifier.

## Fichiers RData

# CyberData.RData

charge l'objet `cyberData` qui est une liste avec `ARTICLES` et `NETKW`.

`NETKW` est un `igraph` qui n'est utilisé que par l'application Keyword (Hadrien). On déplacera cet objet dans un `rds` à part, i.e. `NETKW.rds`.
Nous n'avons pas de code pour re generer `NETKW`, l'objet est à prendre comme une donnée d'entrée.

`ARTICLES`, un data frame de `737 x 812` est utilisé par les applications :
  - `Overview` : pour la carte et le tableau
  - `Geo Semantic` : dans le reactive `clusterCountries`

# citation_cybergeodata.RData

charge l'objet `citation_cybergeodata`, un  data.frame de `885 x 28`. A verifier si le contenu est le même
que les données chargées depuis `cybergeo.csv`.

utilisé uniquement dans l'application `citation network` (Juste)

# citation_kwthemdico.RData

charge deux objets:
 - `citationkwfreqs` : un vecteur de `2784` entiers. Des frequences d'apparition de mots clé (les noms du vecteur)
 - `citationkwthemdico` : un vecteur de `2784`. Correspondances entre les mots clés (2784) et les groupes de mots clés (15)

utilisés seulement pour l'application `citation` (Juste)

# semanticnw.RData

non chargé

# themesPO.Rdata

Charge les objets  :
  - `files` :

```
> head( files )
# A tibble: 6 × 4
     id          name                                                                    path  size
  <int>         <chr>                                                                   <chr> <dbl>
1   279  279_text.txt  /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/279_text.txt  7854
2   286  286_text.txt  /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/286_text.txt  6306
3  6085 6085_text.txt /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/6085_text.txt 20951
4   288  288_text.txt  /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/288_text.txt 20974
5   292  292_text.txt  /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/292_text.txt  8313
6   298  298_text.txt  /Users/petrus/Sync/Data/cybergeo-articles-1996-2015/texts/298_text.txt 25680
```

  - `document.themes` :
  - `themes.termes` :

Ces 3 objets sont retravaillés dans le `global.R`, avec le fichier `poTerms.csv` pour en ressortir un
objet `files` :

```
#'
#' @description LDA analysis output : files = ids and raw files ;
#'   themes.termes = keywords of thematics ; document.themes = probability matrix
load("data/themesPO.Rdata")
files$name = NULL
files$path = NULL

#'
#' @description keywords and themes from LDA
poTerms = read.csv("data/20themes20words.csv", sep=",", dec=".")

nameThemes = c(as.character(poTerms$NAME), "Other")
colnames(document.themes) = nameThemes
files[,3:22] = document.themes
colnames(files)[3:22] = nameThemes
```

Dans ce `files` retravaillé, on retrouve la structure classique: la colonne `id`
qui identifie l'article, la colonne `size` (non utilisée). Les autres colonnes sont
les groupes de mots clés.

On retrouve `854` articles et `20` groupes de mots clé.

On pourra se contenter de stocker ce `files` dans un `.rds`.

## Fichiers csv

# cybergeo.csv

Jeu de données principal. A verifier la correspondance entre ce jeu de données et
l'objet `cyberData$ARTICLES`.

Nous avons évoqué la colonne `TypeDocument` qui nous permet de filtrer certains articles.

Il faut certainement en extraire une partie pour retrouver les jeux de données utilisés dans
les différentes applications.

Ce fichier n'est apparemment chargé explicitement que pour l'application `Full Text`.

# 20themes20words.csv

# articles_Contingency.csv

# df_countryAuthoringToCountryStudied.csv

# docprobasJuste.csv

# docprobasJuste2.csv

devient `justeTerms`. Fichier beaucoup plus volumineux parce qu'il contient
de l'information sur des articles d'autres revues (citant cybergeo et citées par cybergeo).

```
> dim( justeTerms )
[1] 211119     16
```

La variable d'id (`CYBERGEOID`) est fixée à 0 pour des articles qui ne sont
pas issus de cybergeo.


# kwprop.csv

devient `hadriTerms`. Pourquoi :

```
dim(hadriTerms)
[1] 711  11
```

# sentences.csv

# terms.csv

# themesPO.csv
