---
title: "Données utilisées par chaque application"
author: "Romain Francois"
date: "17/02/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Object
======

Ce document recense des informations sur chaque application. Nous nous servirons
de ce document comme base pour uniformiser les données.

Overview
========

Inputs
------

Deux inputs sont utilisés par cette application:
- `dateRange` : un `sliderInput` permettant de selectionner un intervalle entre 1996 et 2015.
- `whatMapped` : un `selectInput` nous permettant de choisir ce qui est
  représenté sur la carte.

Outputs
-------

Trois outputs:
- `cybMap` : un `plotOutput` pour la carte de l'indicateur choisi pendant l'intervalle choisi.
- `statArticles` : un `dataTableOutput`, tableau de résumés des données sur la période considérée.
- `tableName` : un `dataTableOutput` inutilisé.

Données utilisées
-----------------

Le `renderPlot` de `cybMap` récupère des données via un enchainement de reactives, ce renderer utilise :
  - `input$dateRange`
  - `input$whatMapped`
  - `studies`, `authors`, `locals`
  - `world`
  - `files`
  - `cyberData$ARTICLES`

Le `renderDataTable` de `statArticles` utilise aussi le reactive `subsetArticles`. Ce renderer utilise:

  - `cyberData$ARTICLES`
  - `input$dateRange` via le reactiveValues `yearValues` qui pourra disparaitre.
  - `files` qui est mergé avec `cyberData$ARTICLES`. Les données de `files` semblent
    ne pas être utilisées.

L'information principale utilisée dans cette application est contenue dans les
colonnes préfixées par `L_`, `S_` et `A_`. Comment sont générées ces colonnes ?

Modifications
-------------

Ajout de la colonne `year` à `cyberData$ARTICLES`. Cela permet de ne pas avoir à la recalculer à chaque fois. J'ai rajouté ceci après le chargement de `cyberData`

```
cyberData$ARTICLES$year <- as.numeric( substr( as.character(cyberData$ARTICLES$date.1), 1, 4 ) )
```

La fonction `subset_articles` remplace le reactive `subsetArticles` en utilisant
la colonne `year` créée precedemment. Le merge avec les informations de `files`
n'est pas conservé car l'information n'est pas utilisée.

Le code du renderer de `cybMap` a été simplifié et inclus dans
le package (`plot_overview_map`).
